apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-test-app-service
spec:
  selector:
    env: task6os
  type: NodePort
  ports:
    - nodePort: 30000
      port: 81
      targetPort: 80
