apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc1
  labels:
    name: testpvc1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc2
  labels:
    name: testpvc2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
